name: Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt install -y openssh-client

    - name: Enable SSH commands execution
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo apt update
          sudo apt install -y nginx
          nginx -v

    - name: Create Nginx virtual host
      run: |
        sudo cp ./subdomain/app.mercyio.xyz/app.mercyio.xyz.conf /etc/nginx/sites-available/
        ls /etc/nginx/sites-available/
        sudo nginx -t 
        sudo ln -s /etc/nginx/sites-available/app.mercyio.xyz.conf /etc/nginx/sites-enabled/
        sudo mkdir -p /usr/share/nginx/html/.well-known/acme-challenge
        sudo cp ./subdomain/app.mercyio.xyz/index.html /var/www/app.mercyio.xyz
        sudo systemctl reload nginx  # Changed from restart to reload

    - name: Set Up Firewall Rules
      run: |
        sudo ufw allow 80/tcp
        sudo ufw allow 443/tcp
        sudo ufw allow 22/tcp

    - name: Secure the Nginx server
      run: |
        sudo apt update
        sudo snap install --classic certbot
        sudo certbot --version
        sudo certbot --nginx -d app.mercyio.xyz --agree-tos --email udohmercy911@gmail.com --non-interactive --force-renewal
